### ISSUE TITLE
animation of mesh 

### ISSUE THREAD

**Issue by oferidan1** [ycjungSubhuman/DeepDeformable3DCaricatures#4]
Hello, 
thanks for sharing this great paper and code.
I have a question: is it possible to do animation of the mesh output? 
for example, BFM basis enables animation using manipulating of expressions.
is it possible to achieve this effect over the this model? if so, how?
Thanks,
Ofer

**Comment by ycjungSubhuman** [comment]
Animations are available. We show a few examples in our supplementary material: (https://youtu.be/WLMPEaK6E4M). The frames in this animation are generated by applying latent code manipulation gradually (e.g., based on semantic label or handle-based deformation). You can first start with manipulating semantic label and change the script to generate multiple meshes using different edit strengths. After the meshes are generated, render each meshes and you can combine the frames into a video (E.g., using ffmpeg)

**Comment by oferidan1** [comment]
Hi Yucheol Jung,
Thanks for your quick reply.
Let me clarify my question: when using BFM 3dmm model, one can manipulate
the output expression (smile, eye close, etc) by updating the expression
coefficients.
So, is there away to do something similar with your model?
For example, if we would use BFM model as template mesh instead of face
warehouse (or add the expression to face warehouse basis), would the
expression manipulation still work?
Thanks,
Ofer

**Comment by ycjungSubhuman** [comment]
I see. Each element in the latent code does not have clear semantics such as smile, eye close, so you cannot directly manipulate each element by hand intuitively.

To enable traditional shapekey-based animation, You may have to transfer the deformation of each expression shapekey to the generated neutral 3D caricature shape. (E.g., using deformation transfer)

If you use BFM, since the mesh connectivity is preserved, you can apply the expression on top of the result (the expressions in your BFM are just adding vertex displacement). However, the results may not feel natural since the displacements do not consider proper displacement scale or rotation for each part.

Best regards,
Yucheol Jung
________________________________
보낸 사람: oferidan1 ***@***.***>
보낸 날짜: 2022년 9월 20일 화요일 오후 1:45
받는 사람: ycjungSubhuman/DeepDeformable3DCaricatures ***@***.***>
참조: 정유철(컴퓨터공학과) ***@***.***>; State change ***@***.***>
제목: Re: [ycjungSubhuman/DeepDeformable3DCaricatures] animation of mesh (Issue #4)


Hi Yucheol Jung,
Thanks for your quick reply.
Let me clarify my question: when using BFM 3dmm model, one can manipulate
the output expression (smile, eye close, etc) by updating the expression
coefficients.
So, is there away to do something similar with your model?
For example, if we would use BFM model as template mesh instead of face
warehouse (or add the expression to face warehouse basis), would the
expression manipulation still work?
Thanks,
Ofer

**Comment by oferidan1** [comment]
I understand.
Thanks for the clarification.
