### ISSUE TITLE
About ‘horlines.pkl’  and ‘lmks_bc’

### ISSUE THREAD

**Issue by WangJYao** [ycjungSubhuman/DeepDeformable3DCaricatures#5]
What does  'horlines.pkl ' mean by the data it contains?
And what does' lmks_bc' mean? Why update it?

**Comment by ycjungSubhuman** [comment]
horlines.pkl contains landmark candidates for chin. Since fixed 3d chin landmarks does not always stay on the face silhouette, we update chin landmarks iteratively after every pose estimation (See Fig. 4 in Jiang et al. "3D Face Reconstruction With Geometry Details From a Single Image". We use a similar algorithm.).

lmks_bc means "landmarks barycentric coordinates". Because the mesh resolution is low, to accurately express a point on the surface, we need barycentric coordinates.
The landmarks are updated for the reason mentioned above. The updated results are recorded as barycentric coordinates.

Best regards,
Yucheol Jung.
________________________________
보낸 사람: WangJYao ***@***.***>
보낸 날짜: 2022년 9월 24일 토요일 오후 10:11
받는 사람: ycjungSubhuman/DeepDeformable3DCaricatures ***@***.***>
참조: Subscribed ***@***.***>
제목: [ycjungSubhuman/DeepDeformable3DCaricatures] About ‘horlines.pkl’ and ‘lmks_bc’ (Issue #5)


What does 'horlines.pkl ' mean by the data it contains?
And what does' lmks_bc' mean? Why update it?
