### ISSUE TITLE
What are the horlines in staticdata?

### ISSUE THREAD

**Issue by kkpetra** [ycjungSubhuman/DeepDeformable3DCaricatures#7]
Thanks for your great work and I have a question about the files in staticdata. What is the horlines file for? I think it is related to the landmarks but not very clear about the structure. Is there any method to get those coordinates if I want to use other landmark annotation?

Waiting for your reply!

**Comment by ycjungSubhuman** [comment]
For its purpose, you can refer to Issue #5. It is required for accurate fitting to 2D landmarks.

For its structure, it contains a list with the same length as the landmarks.
list[i] = (Possible silhouette landmark candidates for landmark i)

For chin landmarks, we have more than one landmarks in list[i], because there can be multiple candidates for 3D points that matches the silhouette, depending on pose. (Fig. 4 in Jiang et al. "3D Face Reconstruction With Geometry Details From a Single Image") The candidates are generated by 1. Compute a ray form the origin that passes a chin landmark. 2. Rotate the ray along z axis to a fixed angle per landmark. 3. Sample hit surface points on the surface along the rotation. 
For other landmarks, such as mouth or eyes, we only have one candidate for each landmark because the silhouette landmark problem is only dominant in chin area.


Each 3D point is represented in barycentric coordinate. Here I use a pair of (integer, 3D vector).
The integer is face index and the 3D vector is barycentric coordinates. Barycentric coordinates enable picking points inside a triangle, as opposed to the vertex indices that only allow picking points on the vertices.


For custom landmarks, you can generate horlines data by yourself using the procedure described above. Another choice would be to completely ignore the silhouette landmark problem if your 2D landmarks to fit are roughly frontally aligned. In this case, one landmark for each list[i] would be sufficient. You can just convert each landmark to barycentric coordinate and put them there.


For the conversion between 3D positions and barycentric coordinates, there are nice implementations in trimesh.
https://trimsh.org/trimesh.triangles.html#trimesh.triangles.points_to_barycentric 

I hope this helps 
Yucheol Jung

**Comment by kkpetra** [comment]
Thank you so much! And I want to know in the point handle based editing application, if I want to edit a 3D caricature mesh (not from the landmark fitting so does not have the mat file), how can I get the latent?
`latent = torch.Tensor(sp.io.loadmat(os.path.join(root_path, f'{(i):04d}.mat'))['z'])`
